# Upstream cluster
upstream backend_cluster {
    server backend1:5000;
    server backend2:5000;
}

server {
    listen 80;
    server_name localhost;

    # Frontend routing
    location / {
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Requests balancer 
    location /api {
        proxy_pass http://backend_cluster;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # To see which backend answered
        add_header X-Upstream-Server $upstream_addr always;
    }
}